# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Single_Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Single_Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('releaseDate', models.DateField()),
                ('genre', models.CharField(max_length=250)),
                ('lyrics', models.CharField(max_length=2000)),
                ('length', models.DecimalField(decimal_places=3, max_digits=6)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('bands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band')),
                ('playlists', models.ManyToManyField(to='music.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Song_Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('releaseDate', models.DateField()),
                ('genre', models.CharField(max_length=250)),
                ('lyrics', models.CharField(max_length=2000)),
                ('length', models.DecimalField(decimal_places=3, max_digits=6)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('bands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band')),
                ('playlists', models.ManyToManyField(to='music.Playlist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band'),
        ),
        migrations.AddField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Band'),
        ),
    ]
